/**
 * Generate `src/tokens/tokens.css` (Tailwind v4 `@theme` block) from the
 * resolved active tenant tokens.
 *
 * Wired as `prebuild` in `package.json`, so `npm run build` always emits
 * a fresh `tokens.css` for the tenant selected by `process.env.TENANT`
 * (default `spendfreeli`).
 *
 * Manual regeneration:
 *   npm run tokens
 *   TENANT=<partner> npm run tokens
 *
 * The generated `tokens.css` is committed so that a fresh clone can
 * `next dev` without first running the generator. `npm run tokens`
 * before every commit keeps the checked-in file in sync — CI should
 * later assert no drift.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { tokens, tenantName } from '../src/tokens';
import type { Tokens } from '../src/tokens/base';

const OUTPUT_PATH = resolve(process.cwd(), 'src/tokens/tokens.css');

function emitVars(t: Tokens): string {
  const lines: string[] = [];

  lines.push('  /* Colors */');
  lines.push(`  --color-primary: ${t.colors.primary};`);
  lines.push(`  --color-primary-dark: ${t.colors.primaryDark};`);
  lines.push(`  --color-primary-light: ${t.colors.primaryLight};`);
  lines.push(`  --color-background: ${t.colors.background};`);
  lines.push(`  --color-surface: ${t.colors.surface};`);
  lines.push(`  --color-text-primary: ${t.colors.text.primary};`);
  lines.push(`  --color-text-secondary: ${t.colors.text.secondary};`);
  lines.push(`  --color-text-inverse: ${t.colors.text.inverse};`);
  lines.push(`  --color-border: ${t.colors.border};`);
  lines.push(`  --color-success: ${t.colors.success};`);
  lines.push(`  --color-error: ${t.colors.error};`);
  lines.push('');

  lines.push('  /* Fonts */');
  lines.push(`  --font-heading: ${t.fonts.heading};`);
  lines.push(`  --font-body: ${t.fonts.body};`);
  lines.push(`  --font-sans: ${t.fonts.body};`);
  lines.push('');

  // NB: `--spacing-*` is intentionally NOT emitted. In Tailwind v4 the
  // sizing scale (`p-*`, `m-*`, `gap-*`, `max-w-*`, `w-*`, `h-*`) all
  // read from `--spacing-<key>`. Defining `--spacing-lg: 1.5rem` for
  // padding also hijacks `max-w-lg` to 1.5rem — silently breaking
  // container widths. Components use Tailwind's numeric spacing scale
  // (`p-6`, `mt-8`, etc.) which multiplies the built-in `--spacing`
  // base (0.25rem). See `src/tokens/base.ts` for the architecture note.

  lines.push('  /* Radii */');
  for (const [key, value] of Object.entries(t.radius)) {
    lines.push(`  --radius-${key}: ${value};`);
  }
  lines.push('');

  lines.push('  /* Shadows */');
  for (const [key, value] of Object.entries(t.shadows)) {
    lines.push(`  --shadow-${key}: ${value};`);
  }

  return lines.join('\n');
}

const output = `/*
 * AUTO-GENERATED — DO NOT EDIT.
 *
 * Regenerated by scripts/generate-tokens-css.ts on every build.
 * Source of truth: src/tokens/tenants/${tenantName}.ts (via src/tokens/index.ts).
 *
 * To modify token values, edit the tenant file. To switch tenants,
 * set the TENANT env var: \`TENANT=<name> npm run build\`.
 */

@theme {
${emitVars(tokens)}
}
`;

writeFileSync(OUTPUT_PATH, output);
console.log(`✓ tokens.css generated for tenant "${tenantName}"`);
